// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "user_details.h"

#if TARGET_OS_OSX
@import FlutterMacOS;
#else
@import Flutter;
#endif

static BOOL __attribute__((unused)) FLTPigeonDeepEquals(id _Nullable a, id _Nullable b) {
  if (a == b) {
    return YES;
  }
  if (a == nil) {
    return b == [NSNull null];
  }
  if (b == nil) {
    return a == [NSNull null];
  }
  if ([a isKindOfClass:[NSNumber class]] && [b isKindOfClass:[NSNumber class]]) {
    return [a isEqual:b] || (isnan([(NSNumber *)a doubleValue]) && isnan([(NSNumber *)b doubleValue]));
  }
  if ([a isKindOfClass:[NSArray class]] && [b isKindOfClass:[NSArray class]]) {
    NSArray *arrayA = (NSArray *)a;
    NSArray *arrayB = (NSArray *)b;
    if (arrayA.count != arrayB.count) {
      return NO;
    }
    for (NSUInteger i = 0; i < arrayA.count; i++) {
      if (!FLTPigeonDeepEquals(arrayA[i], arrayB[i])) {
        return NO;
      }
    }
    return YES;
  }
  if ([a isKindOfClass:[NSDictionary class]] && [b isKindOfClass:[NSDictionary class]]) {
    NSDictionary *dictA = (NSDictionary *)a;
    NSDictionary *dictB = (NSDictionary *)b;
    if (dictA.count != dictB.count) {
      return NO;
    }
    for (id keyA in dictA) {
      id valueA = dictA[keyA];
      BOOL found = NO;
      for (id keyB in dictB) {
        if (FLTPigeonDeepEquals(keyA, keyB)) {
          id valueB = dictB[keyB];
          if (FLTPigeonDeepEquals(valueA, valueB)) {
            found = YES;
            break;
          } else {
            return NO;
          }
        }
      }
      if (!found) {
        return NO;
      }
    }
    return YES;
  }
  return [a isEqual:b];
}

static NSUInteger __attribute__((unused)) FLTPigeonDeepHash(id _Nullable value) {
  if (value == nil || value == (id)[NSNull null]) {
    return 0;
  }
  if ([value isKindOfClass:[NSNumber class]]) {
    NSNumber *n = (NSNumber *)value;
    double d = n.doubleValue;
    if (isnan(d)) {
      // Normalize NaN to a consistent hash.
      return (NSUInteger)0x7FF8000000000000;
    }
    if (d == 0.0) {
      // Normalize -0.0 to 0.0 so they have the same hash code.
      d = 0.0;
    }
    return @(d).hash;
  }
  if ([value isKindOfClass:[NSArray class]]) {
    NSUInteger result = 1;
    for (id item in (NSArray *)value) {
      result = result * 31 + FLTPigeonDeepHash(item);
    }
    return result;
  }
  if ([value isKindOfClass:[NSDictionary class]]) {
    NSUInteger result = 0;
    NSDictionary *dict = (NSDictionary *)value;
    for (id key in dict) {
      result += ((FLTPigeonDeepHash(key) * 31) ^ FLTPigeonDeepHash(dict[key]));
    }
    return result;
  }
  return [value hash];
}


@interface UserDetails ()
+ (UserDetails *)fromList:(NSArray<id> *)list;
+ (nullable UserDetails *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation UserDetails
+ (instancetype)makeWithUid:(nullable NSString *)uid
    email:(nullable NSString *)email
    displayName:(nullable NSString *)displayName {
  UserDetails* pigeonResult = [[UserDetails alloc] init];
  pigeonResult.uid = uid;
  pigeonResult.email = email;
  pigeonResult.displayName = displayName;
  return pigeonResult;
}
+ (UserDetails *)fromList:(NSArray<id> *)list {
  UserDetails *pigeonResult = [[UserDetails alloc] init];
  pigeonResult.uid = GetNullableObjectAtIndex(list, 0);
  pigeonResult.email = GetNullableObjectAtIndex(list, 1);
  pigeonResult.displayName = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable UserDetails *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [UserDetails fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.uid ?: [NSNull null],
    self.email ?: [NSNull null],
    self.displayName ?: [NSNull null],
  ];
}
- (BOOL)isEqual:(id)object {
  if (self == object) {
    return YES;
  }
  if (![object isKindOfClass:[self class]]) {
    return NO;
  }
  UserDetails *other = (UserDetails *)object;
  return FLTPigeonDeepEquals(self.uid, other.uid) && FLTPigeonDeepEquals(self.email, other.email) && FLTPigeonDeepEquals(self.displayName, other.displayName);
}

- (NSUInteger)hash {
  NSUInteger result = [self class].hash;
  result = result * 31 + FLTPigeonDeepHash(self.uid);
  result = result * 31 + FLTPigeonDeepHash(self.email);
  result = result * 31 + FLTPigeonDeepHash(self.displayName);
  return result;
}
@end

@interface nullUserDetailsPigeonCodecReader : FlutterStandardReader
@end
@implementation nullUserDetailsPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [UserDetails fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullUserDetailsPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullUserDetailsPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[UserDetails class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface nullUserDetailsPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullUserDetailsPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullUserDetailsPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullUserDetailsPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetUserDetailsCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullUserDetailsPigeonCodecReaderWriter *readerWriter = [[nullUserDetailsPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
