// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

@import Foundation;

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class UserDetails;

@interface UserDetails : NSObject
+ (instancetype)makeWithUid:(nullable NSString *)uid
    email:(nullable NSString *)email
    displayName:(nullable NSString *)displayName;
@property(nonatomic, copy, nullable) NSString * uid;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * displayName;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetUserDetailsCodec(void);
NS_ASSUME_NONNULL_END
